---
- name: install setfacl support
  become: yes
  apt: pkg=acl
  tags: install
- name: python-psycopg2 | install
  apt: name=python-psycopg2 state=present
  tags: install
- name: postgresql9.3 | install
  apt: name=postgresql state=present
  tags: install
- name: Ensure the PostgreSQL service is running 
  service: name=postgresql state=started enabled=yes
  tags: install
- name: database  | create
  become: true
  become_user: postgres
  #postgresql_db: name:{{ database_name }} state=present
  postgresql_db: name={{ database_name }} encoding='UTF-8' lc_collate='en_US.UTF-8' lc_ctype='en_US.UTF-8' template='template0' state=present
  tags: kazbek_db_create
- name: postgres user | create
  become: true
  become_user: postgres
  postgresql_user: name={{ user_name  }} password={{ user_password }} role_attr_flags=SUPERUSER
  notify: restart postgresql
  tags: users_create 
