---
- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: MySQL package | install
  apt: name=mysql-server-5.6 state=present
  tags: install

- name: install python mysql bindings
  apt: name=python-mysqldb state=installed
  
- name: create user and password
  mysql_user: name={{ user_name }} password={{ user_password }} priv=*.*:ALL,GRANT state=present
  tags: set_privileges
