---
- name: add repo for php5-5.6
  apt_repository: repo='ppa:ondrej/php5-5.6' update_cache=yes
- name: python-software-properties
  apt: name=python-software-properties state=present  
- name: php5.0 | install
  apt: name={{ item }} state=installed
  with_items:
  - php5
  - php5-common
  - php5-mysql
  - php5-pgsql
  - php5-cli
  - php5-curl
  - php5-gd
  - php5-dev
  - php5-mcrypt
  - php5-memcache
  - php5-memcached
  - php5-sqlite
  - php-apc
  - php-pear
  - libapache2-mod-php5
- name: mod php5.0 | enable
  apache2_module: state=present name=php5
  notify: restart apache
  tags: enable_php5_mod
